### ISSUE TITLE
The plugin cannot find my scala

### ISSUE THREAD

**Issue by davidshen84** [saturday06/gradle-android-scala-plugin#22]
My environment is Windows 7 64bit, scala 2.11. I have update my `build.gradle` file as indicated in the README file. When I run `gradlew --debu` I got the following error. Looks like it cannot find my scala. I tried to set the `CLASSPATH` environment variable, but doesn't help.

```
15:38:18.492 [ERROR] [org.gradle.BuildExceptionReporter]
15:38:18.493 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:38:18.493 [ERROR] [org.gradle.BuildExceptionReporter]
15:38:18.493 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:38:18.493 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
15:38:18.493 [ERROR] [org.gradle.BuildExceptionReporter] > groovy.lang.MissingMethodException: No signature of method: java.net.URLClassLoader.close() is applicable for argument types: () values: []
Possible solutions: use([Ljava.lang.Object;), use(java.util.List, groovy.lang.Closure), use(java.lang.Class, groovy.lang.Closure), collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure)
15:38:18.493 [ERROR] [org.gradle.BuildExceptionReporter]
15:38:18.494 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:493)
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:80)
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
15:38:18.500 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
15:38:18.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
15:38:18.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
15:38:18.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
15:38:18.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
15:38:18.501 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
15:38:18.502 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:46)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.main(Main.java:37)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
15:38:18.503 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: java.net.URLClassLoader.close() is applicable for argument types: () values: []
Possible solutions: use([Ljava.lang.Object;), use(java.util.List, groovy.lang.Closure), use(java.lang.Class, groovy.lang.Closure), collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
15:38:18.504 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        ... 29 more
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.MissingMethodException: No signature of method: java.net.URLClassLoader.close() is applicable for argument types: () values: []
Possible solutions: use([Ljava.lang.Object;), use(java.util.List, groovy.lang.Closure), use(java.lang.Class, groovy.lang.Closure), collect(), collect(groovy.lang.Closure), collect(java.util.Collection, groovy.lang.Closure)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        at jp.leafytree.gradle.AndroidScalaPlugin.scalaVersionFromClasspath(AndroidScalaPlugin.groovy:269)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        at jp.leafytree.gradle.AndroidScalaPlugin$scalaVersionFromClasspath.callStatic(Unknown Source)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        at jp.leafytree.gradle.AndroidScalaPlugin.addAndroidScalaCompileTask(AndroidScalaPlugin.groovy:313)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        at jp.leafytree.gradle.AndroidScalaPlugin$_apply_closure1_closure17.doCall(AndroidScalaPlugin.groovy:88)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        at jp.leafytree.gradle.AndroidScalaPlugin$_apply_closure1.doCall(AndroidScalaPlugin.groovy:87)
15:38:18.505 [ERROR] [org.gradle.BuildExceptionReporter]        ... 36 more
15:38:18.508 [ERROR] [org.gradle.BuildExceptionReporter]
15:38:18.508 [LIFECYCLE] [org.gradle.BuildResultLogger]
15:38:18.509 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

**Comment by frait** [comment]
@davidshen84 
concerning the last error you experienced with the shared paths: You can solve this by going to Project Structure -> Modules -> "Your Module" -> Paths. There check "Inherit project compile output path" rather then "Use module compile output path". Or with the latter option you could specify two different paths.
