### ISSUE TITLE
Error:Cause: scala/util/Properties$ : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ssuukk** [saturday06/gradle-android-scala-plugin#66]
My project used to build before, now (all of the sudden) it fails with:

Error:Cause: scala/util/Properties$ : Unsupported major.minor version 52.0

I couldn't get any info on this error, the only thing I discovered that it is caused by this line in build.gradle:

apply plugin: 'jp.leafytree.android-scala'

More info here: http://stackoverflow.com/questions/31492714/building-android-app-with-scala-bad-class-file-magic/31494910#31494910

Might that be due to some scala class being compiled to java 8? If yes, what can I do? I tried everything, including removing android studio, caches, sbt, gradle, scala jars, libraries, anything named "scala" etc.

Some more info from log:

Caused by: java.lang.UnsupportedClassVersionError: scala/util/Properties$ : Unsupported major.minor version 52.0
	at java_lang_ClassLoader$loadClass.call(Unknown Source)
	at jp.leafytree.gradle.AndroidScalaPlugin.scalaVersionFromClasspath(AndroidScalaPlugin.groovy:132)
	at jp.leafytree.gradle.AndroidScalaPlugin$scalaVersionFromClasspath$0.callStatic(Unknown Source)
	at jp.leafytree.gradle.AndroidScalaPlugin.addAndroidScalaCompileTask(AndroidScalaPlugin.groovy:184)
	at jp.leafytree.gradle.AndroidScalaPlugin$_apply_closure4_closure18.doCall(AndroidScalaPlugin.groovy:84)
	at jp.leafytree.gradle.AndroidScalaPlugin$_apply_closure4.doCall(AndroidScalaPlugin.groovy:83)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)

**Comment by saturday06** [comment]
That log shows that `scala/util/Properties` (scala-library jar) was compiled to java8.
I guess, your project uses scala-library 2.12.0-M2 . It's compiled to java8 class file.
If it doesn't use that version, please upload your `build.gradle` for analysis

**Comment by ssuukk** [comment]
Before I bother you with log - where is this library located, so I can check if it is indeed for j8. And if it is indeed - how do I replace it with version for java7?

**Comment by saturday06** [comment]
Following code downloads and uses scala-library 2.12.0-M1. 
```
    compile 'org.scala-lang:scala-library:2.+'
```
It's unsupported by gradle-android-scala-plugin because scala-library 2.12.* depends on java8 (see also [README.md](https://github.com/saturday06/gradle-android-scala-plugin/blob/master/README.md#supported-versions))
 
Please use scala-library 2.11 series.
```
    compile 'org.scala-lang:scala-library:2.11.+'
```

**Comment by saturday06** [comment]
You can check your scala-library version to execute `./gradlew dependencies -p $your_app_project_dir | grep scala-library`

**Comment by ssuukk** [comment]
Aaaah... I wouldn't have thought that a minor version number would bring such a big change. Thanks for your response, I guess you can close this.
